[package]
name = "testkit-core"
description = "Core utilities for the Soroban Testkit testing framework"
keywords = ["soroban", "stellar", "testing", "budget", "blockchain"]
categories = ["development-tools::testing"]
documentation = "https://stellar-crucible.github.io/soroban-testkit/crates/core.html"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
soroban-sdk = { workspace = true }
soroban-env-host = { workspace = true }
